---
- name: Update apt pkg list
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install python3
  ansible.builtin.apt:
    pkg:
    - python3-poetry
    - python3-cachecontrol  # HACK: poetry breaks without this
  become: yes

- name: Ensure poetry is available
  command: "poetry --version"
