---
- name: Update apt pkg list
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install deps
  ansible.builtin.apt:
    pkg:
    - software-properties-common
  become: yes

- name: Add deadsnakes apt repository
  ansible.builtin.apt_repository:
    repo: "ppa:deadsnakes/ppa"
    state: present
  become: yes

- name: Install python3
  ansible.builtin.apt:
    pkg:
    - software-properties-common
    - python3.10-full
  become: yes

- name: Ensure pip is available
  command: "python3.10 -m ensurepip"

- name: Ensure pip is updated
  command: "python3.10 -m pip install --upgrade pip"

- name: Ensure poetry is available
  command: "python3.10 -m pip install --user poetry"
