---
- name: Update apt pkg list
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Ensure redis and deps are present
  apt:
    pkg:
      - redis
      - redis-server
    state: present
  become: true

- name: Ensure Redis is started
  service:
    name: redis
    state: started
    enabled: yes
  become: yes

- name: Ensure Redis parameters are configured
  lineinfile:
    dest: /etc/redis/redis.conf
    regexp: "{{ item.line_to_match }}"
    line: "{{ item.line_to_configure }}"
  with_items:
    - { line_to_match: "maxmemory", line_to_configure: "maxmemory 512MB" }
    - { line_to_match: "bind", line_to_configure: "bind 127.0.0.1" }
    - { line_to_match: "maxmemory-policy", line_to_configure: "maxmemory-policy allkeys-lru" }
    - { line_to_match: "maxmemory-samples", line_to_configure: "maxmemory-samples 5" }
  register: redis_conf
  become: yes

- name: Ensure redis service is restarted
  service:
    name: redis
    state: restarted
  when: redis_conf.changed
  become: yes
