---
- name: Checkout website
  git:
    repo: https://github.com/h3nnn4n/{{ repo_name }}
    dest: "{{ project_folder }}/{{ repo_name }}"
    version: "{{ deploy_branch }}"

- name: Install project deps with Poetry
  command: "~/.local/bin/poetry install"
  args:
    chdir: "{{ project_folder }}/{{ repo_name }}/website"

- name: Setup .env file
  template:
    src: dot_env
    dest: "{{ project_folder }}/{{ repo_name }}/website/.env"
    owner: devops
    group: devops
    mode: '0400'  # Read only to owner

- name: Run django collectstatic
  shell: |
    DJANGO_SETTINGS_MODULE=website.settings \
    ~/.local/bin/poetry run python3 manage.py collectstatic --no-input
  args:
    executable: /bin/bash
    chdir: "{{ project_folder }}/{{ repo_name }}/website"

- name: Stop gunicorn
  shell: |
    kill $(cat {{ project_folder }}/{{ repo_name }}/website/gunicorn.pid)
  ignore_errors: true

- name: Start gunicorn
  shell: |
    DJANGO_SETTINGS_MODULE=website.settings \
    ~/.local/bin/poetry run gunicorn \
      website.wsgi \
      --bind=localhost:8000 \
      --access-logfile=access.log \
      --log-level=info \
      --log-file=server.log \
      --pid={{ project_folder }}/{{ repo_name }}/website/gunicorn.pid \
      --preload \
      --timeout=2 \
      --threads={{ gunicorn_thread_count | default('2') }} \
      --workers={{ gunicorn_worker_count | default('2') }} & disown %
  args:
    executable: /bin/bash
    chdir: "{{ project_folder }}/{{ repo_name }}/website"
